Rouuting works with error
setting the 'to' on router link as ':to='stepStore.stepName'' (notice : before to) allows routing to the current state of stepName to work. BUT getting error 'Uncaught TypeError: this.updateStep is not a function' when the actions are used (fowardStepAction, backStepAction)