development (#18)
* old component data entry (#1)

* Company Name component

created form with label for user input of company name

* Pinia Store Data Flows

Setup pinia 'reportStore', added companyName - string, fixedCosts - array of objects. Imported into FixedCosts.vue. Looped fixed cost name with v-for. Next will flow through data to sub-component as props ('FixedCostsDetails') where data table will live.

* Pinia Data through Subcomponent

Pinia Store data was passed as props through FixedCosts.vue in v-for='...' into subComponent <FCD :.../>. Had to add props in FixedCostDetails.vue script tag.

* Code Break

Working on how to use a getter in store to sum value of fixedCost.amount

* Pinia Getter works

The reportStore calculates the total fixed cost within getter->totalFixedCosts and is passed through to FixedCosts.vue as property interpolation. Next will try to pass as prosp into subcomponent

* Setup Actions, user input changes state in reportStore

* checked out old commit to push to development and lock in

* added some inline styling for legibility

* chore: add ids to fixed costs

* chore: update project layout and structure

* installed Vue-Router

* review (#2)

* chore: add ids to fixed costs

* chore: update project layout and structure

---------

Co-authored-by: Dan Andrade <dan@cloudspot.io>

* installed Vue-Router (#3)

* Fixed Cost Table Populates

Seperated the fixed cost code in to sub-components of FixedCostDetails (FixedCostTable, FixedCostDataInput). In fixedCostDatInput set up refs with type for each element, added v-model on each input, @submit.prevent on the form, and a Add button which calls addFixedCostAction from the reportStore. The new fixed cost objects pushed into the fixedCosts state array populate in the FixedCostTable.

* Used Prettier on code. Added more types.ts files & imported

* Save to checkout

* component router setup (#5)

* chore: add ids to fixed costs

* chore: update project layout and structure

* installed Vue-Router

* Save to checkout

---------

Co-authored-by: Dan Andrade <dan@cloudspot.io>

* Created view for CompanyNameDetails

seperated out the CompanyNameDetails functionality into it's own file within src/components/views. Imported it into CobdForm.vue which will be the main page which changes views (steps in wizard)

* refactor company name step (#6)

* chore: add ids to fixed costs

* chore: update project layout and structure

* installed Vue-Router

* Save to checkout

* Created view for CompanyNameDetails

seperated out the CompanyNameDetails functionality into it's own file within src/components/views. Imported it into CobdForm.vue which will be the main page which changes views (steps in wizard)

---------

Co-authored-by: Dan Andrade <dan@cloudspot.io>

* Duplicate gone (somehow) commit to compare with broken branch

* Confirming hotfix works

* hotfix duplicate fixed cost components (#7)

* chore: add ids to fixed costs

* chore: update project layout and structure

* installed Vue-Router

* Fixed Cost Table Populates

Seperated the fixed cost code in to sub-components of FixedCostDetails (FixedCostTable, FixedCostDataInput). In fixedCostDatInput set up refs with type for each element, added v-model on each input, @submit.prevent on the form, and a Add button which calls addFixedCostAction from the reportStore. The new fixed cost objects pushed into the fixedCosts state array populate in the FixedCostTable.

* Used Prettier on code. Added more types.ts files & imported

* Duplicate gone (somehow) commit to compare with broken branch

* Confirming hotfix works

---------

Co-authored-by: Dan Andrade <dan@cloudspot.io>

* Renamed and reorganized files and folders

* added node to compilerOptions/types in tsconfig.json to enable process.env.BASE_URL in router->index.ts

* Added router logic/code to router/index.js and CobdForm.vue

* added npm install --save-dev @vue/cli-service

* Vue Router Works

Used Has Mode History

* CobdFooter buttons hold the router links

* Closing Feature to start new one for router state

* Router set up for all Steps

Mapped an array in index.ts to generate each route object. Will abstract that array eventually

* end of night commit & PR

* feature vue router (#8)

* added node to compilerOptions/types in tsconfig.json to enable process.env.BASE_URL in router->index.ts

* Added router logic/code to router/index.js and CobdForm.vue

* added npm install --save-dev @vue/cli-service

* Vue Router Works

Used Has Mode History

* CobdFooter buttons hold the router links

* Closing Feature to start new one for router state

* Router set up for all Steps

Mapped an array in index.ts to generate each route object. Will abstract that array eventually

* end of night commit & PR

* Cleaning up styling

* Abstracted the options in fixed cost category

* Formatting and abstracted fixed cost period options

* refactor remove duplication (#9)

* Abstracted the options in fixed cost category

* Formatting and abstracted fixed cost period options

* commit to create new branch

* added store/stepStore.ts

* Actions on store and component

Added actions to stepStore.ts (for incrementing and decrementing the step state). Attached actions with v-on (@) to buttons in CobdFooter)

* Imported stepsArray into stepStore.js

* stepName updates

Created a gettin in stepStore.ts 'updateStep', returned the state.stepName = stepsArray[state.stepName].path and called the getting in each action (forward..., back....). Had to set the type on the updateState getter to 'any'

* Added views/Home.vue as step 0

* fixed router for home link

In stepsArray changed Home path from '' to '/'. In routes/index.ts set the if condition to step.path === '/#'. Now works as expected. Clicking home brings to home.

* Rouuting works with error

setting the 'to' on router link as ':to='stepStore.stepName'' (notice : before to) allows routing to the current state of stepName to work. BUT getting error 'Uncaught TypeError: this.updateStep is not a function' when the actions are used (fowardStepAction, backStepAction)

* Error fixed

Removed getter and put logic in actions to stop error

* set min/max for stepNum

using conitional inside stepStore actions (back.... forward...) set min/max value of this.stepNum constrain within stepsArray

* Clean up

Removed comments, removed unneeded arguments from actions, code formatting

* feature vue router (#10)

* added store/stepStore.ts

* Actions on store and component

Added actions to stepStore.ts (for incrementing and decrementing the step state). Attached actions with v-on (@) to buttons in CobdFooter)

* Imported stepsArray into stepStore.js

* stepName updates

Created a gettin in stepStore.ts 'updateStep', returned the state.stepName = stepsArray[state.stepName].path and called the getting in each action (forward..., back....). Had to set the type on the updateState getter to 'any'

* Added views/Home.vue as step 0

* fixed router for home link

In stepsArray changed Home path from '' to '/'. In routes/index.ts set the if condition to step.path === '/#'. Now works as expected. Clicking home brings to home.

* Rouuting works with error

setting the 'to' on router link as ':to='stepStore.stepName'' (notice : before to) allows routing to the current state of stepName to work. BUT getting error 'Uncaught TypeError: this.updateStep is not a function' when the actions are used (fowardStepAction, backStepAction)

* Error fixed

Removed getter and put logic in actions to stop error

* set min/max for stepNum

using conitional inside stepStore actions (back.... forward...) set min/max value of this.stepNum constrain within stepsArray

* Clean up

Removed comments, removed unneeded arguments from actions, code formatting

* Commit to checkout development

* Removed 's' in FinalReportStep

* removed extra FixedCostsStep file in FixedCostComponents

* Fixed cost refactor, On FinalReportStep

Moved the data binding (v-for, key) from the parent step into FixedCostsTable to reduce duplication on imports and preserve styling. Imported FixedCostsTable into FinalReportStep

* feature data to report (#11)

* Commit to checkout development

* removed extra FixedCostsStep file in FixedCostComponents

* Fixed cost refactor, On FinalReportStep

Moved the data binding (v-for, key) from the parent step into FixedCostsTable to reduce duplication on imports and preserve styling. Imported FixedCostsTable into FinalReportStep

* refactor form reusability (#12)

* Commit to checkout development

* removed extra FixedCostsStep file in FixedCostComponents

* Fixed cost refactor, On FinalReportStep

Moved the data binding (v-for, key) from the parent step into FixedCostsTable to reduce duplication on imports and preserve styling. Imported FixedCostsTable into FinalReportStep

* Changing task to building a reusuable form, will delete this branch

* Data wont pass to Pinia

Once the form element is abstracted in it's own file I can't get the data to flow through to pinia store

* Commit to save

* DataInput works with error

DataInput now passes data through FixedCostData to Pinia store, but still recieving console error: '[Vue warn]: Component emitted event update:modelValue but it is neither declared in the emits option nor as an onUpdate:modelValue prop.'

* Abstraced option works

Needed to v-bind value on the option (i.e. :value='' instead of value='') to get it to pass data through.

* Created reusable Select

Created a DataSelect component that can be reused across forms. Sends option to the pinia store and to the form from there.

* Removed console logs, comments, unused imports

* component variable costs (#13)

* Commit to checkout development

* removed extra FixedCostsStep file in FixedCostComponents

* Fixed cost refactor, On FinalReportStep

Moved the data binding (v-for, key) from the parent step into FixedCostsTable to reduce duplication on imports and preserve styling. Imported FixedCostsTable into FinalReportStep

* Added VariableCostsComponents

Mirroring Fixed costs, created VariableCosts components and subcomponents. Utilized existing data/select-input, etc.

* refactor router views (#14)

* Commit to checkout development

* removed extra FixedCostsStep file in FixedCostComponents

* Fixed cost refactor, On FinalReportStep

Moved the data binding (v-for, key) from the parent step into FixedCostsTable to reduce duplication on imports and preserve styling. Imported FixedCostsTable into FinalReportStep

* moved step components to /components/StepComponents

* router-view in App.vue to render main view (Cobd.vue) and router-viw in CobdForm.vue to render all step components as children

* Changed App.vue to be in the format suggested by Dan

* removed commented out code, extranous p tags, etc, to clean things up

* removed import, setup, style tags from App.vue

* Refactored index.ts, writing out all paths instead of array.map

* Commit to switch branch

* component booking income step (#15)

* New types, store

Created stores/bookingIncomeStore.ts and types/BookingIncomeState.ts

* Input works with errors

with @blur event handler and <data-input /> the data passes from the input to the store to the report component. getting error '[Vue Warn: Component emitted event 'update:modelValue'  but it is neither declared in the emites optin nor as an 'onUpdate:modelVale''

* Component Complete

Three data-inputs added, with associated actions in bookingIcomeStore all send data through pinia to the finalReportStep

* Component Finished

Created store and component for Owners Draw data, passed data to the final report component

* Component Finished (#16)

Created store and component for Owners Draw data, passed data to the final report component

* refactor clean up (#17)

* Component Finished

Created store and component for Owners Draw data, passed data to the final report component

* Prettier on all files for consistency

* Seperated Fixed Cost Store

Created a fixedCostStore.ts and removed all fixed cost opeations out of the reportStore.ts, updated the rest of the fixed cost components.

* Seperated Variable Cost Store

* Fixed bug, errors in FixedCostDataInput, VariableCostDataInput

Data inputs were not flowing through pinia. Had to remove the '' around the ref name (e.g. v-model=fixedCostName not ...'fixedCostName'). Needed to add :modelValue to the emits option in DataSelect.vue (e.g. const emit...(e: 'update:modelValue'...)

* Test and clean up

Steped through end to end, all data pulls through. Removed $ where they didn't belong, added variable-cost-table to finalReportStep

* Changed reportStore to companyStore

All components have their own store now. Will then create an addional reportStore to take in and calculate all the date to pass to the FinalReportStep component

* removed console.logs and dummy cost data

---------

Co-authored-by: Dan Andrade <dan@cloudspot.io>